AWSTemplateFormatVersion: 2010-09-09

Parameters:

  DomainName:
    Type: String

  RegionalCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>

Resources:

# Cognito User Pool

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref AWS::StackName

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      CustomDomainConfig:
         CertificateArn: !Ref RegionalCertificateArn
      Domain: !Sub "auth.${DomainName}"
      UserPoolId: !Ref UserPool

# Cognito Resource Servers



# Cognito Clients

  AppleIdLoginClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: appleid-logins
      RefreshTokenValidity: 30
      UserPoolId: !Ref UserPool
      CallbackURLs:
        - !Sub "https://contributors.${DomainName}/oauth2/appleid/tokens"
        - !Sub "https://auth.${DomainName}/oauth2/idpresponse"
      LogoutURLs:
        - !Sub "https://contributors.${DomainName}/oauth2/appleid/logout"
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid

# Stack Outputs

Outputs:

  CognitoUserPoolArn:
    Value: !GetAtt UserPool.Arn

  AppleIdLoginClientId:
    Value: !Ref AppleIdLoginClient
