AWSTemplateFormatVersion: 2010-09-09

Parameters:

  DomainName:
    Type: String

  RegionalCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>

Resources:

# Cognito User Pool

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref AWS::StackName

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      CustomDomainConfig:
         CertificateArn: !Ref RegionalCertificateArn
      Domain: !Sub "auth.${DomainName}"
      UserPoolId: !Ref UserPool

# Cognito Resource Servers

  ContributorsApi:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: contributors-api
      Name: Contributors API
      UserPoolId: !Ref UserPool
      Scopes:
        - ScopeName: full_access
          ScopeDescription: Default scope

  TitlesApi:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: titles-api
      Name: Titles API
      UserPoolId: !Ref UserPool
      Scopes:
        - ScopeName: full_access
          ScopeDescription: Default scope

# Cognito Clients

  AppleIdLoginClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: appleid-logins
      RefreshTokenValidity: 30
      UserPoolId: !Ref UserPool
      CallbackURLs:
        - !Sub "https://contributors.${DomainName}/oauth2/appleid/token"
        - !Sub "https://auth.${DomainName}/oauth2/idpresponse"
        - !Sub "https://${DomainName}"
      LogoutURLs:
        - !Sub "https://contributors.${DomainName}/oauth2/appleid/logout"
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - openid
        - contributors-api/full_access

# Auth Code Sign In URL: https://auth.{DOMAIN}/login?response_type=code&client_id={CLIENT_ID}&redirect_uri=https://contributors.${DOMAIN}/oauth2/appleid/token
# Implicit Sign In URL: https://auth.{DOMAIN}/login?response_type=token&client_id={CLIENT_ID}&redirect_uri=https://{DOMAIN}

# Stack Outputs

Outputs:

  CognitoUserPoolArn:
    Value: !GetAtt UserPool.Arn

  AppleIdLoginClientId:
    Value: !Ref AppleIdLoginClient
