AWSTemplateFormatVersion: 2010-09-09

Resources:

# Global DynamoDB Table

# Must configure global table in the console at this time.

  CommunityPatchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: contributor_id
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: search_index
          AttributeType: S
        - AttributeName: title_id
          AttributeType: S
        - AttributeName: alias
          AttributeType: S

      KeySchema:
        - AttributeName: contributor_id
          KeyType: HASH
        - AttributeName: type
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: ContributorSummaries
          KeySchema:
            - AttributeName: contributor_id
              KeyType: HASH
            - AttributeName: title_id
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - summary

        - IndexName: TitleSearch
          KeySchema:
            - AttributeName: search_index
              KeyType: HASH
            - AttributeName: title_id
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - contributor_id
              - summary

        - IndexName: ContributorAliasLookup
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: alias
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - contributor_id

      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

# Stack Outputs

Outputs:

  CommunityPatchTableName:
    Value: !Ref CommunityPatchTable
