AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:

  Namespace:
    Type: String

  DomainName:
    Type: AWS::SSM::Parameter::Value<String>

  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>

  RegionalCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>

  ContributorsTableName:
    Type: AWS::SSM::Parameter::Value<String>

  EmailServiceTopicArn:
    Type: AWS::SSM::Parameter::Value<String>

# SAM Globals

Globals:
  Function:
    Runtime: python3.7
    Handler: index.lambda_handler
    Tracing: PassThrough
    Environment:
      Variables:
        CONTRIBUTORS_TABLE: !Ref ContributorsTableName
        DOMAIN_NAME: !Ref DomainName
        EMAIL_SERVICE_TOPIC: !Ref EmailServiceTopicArn
        NAMESPACE: !Ref Namespace

Resources:

# API Gateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      TracingEnabled: true

      Models:
        Registration:
          type: object
          properties:
            email:
              id: /properties/email
              type: string
              pattern: '^[^@\s]+@[^@\s]+\.[^@\s]+$'
            name:
              id: /properities/name
              type: string
              pattern: '^\S+$'
          required:
            - email
            - name

  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Sub 'contributors.${DomainName}'
      RegionalCertificateArn: !Ref RegionalCertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiBasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiCustomDomain
      RestApiId: !Ref ApiGateway
      Stage: Prod
    DependsOn:
      - ApiGateway
      - ApiGatewayProdStage
      - ApiCustomDomain

  RegionalRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub 'contributors.${DomainName}'
      SetIdentifier: !Sub 'contributors-api-${AWS::Region}'
      AliasTarget:
        DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Region: !Ref AWS::Region
      Type: A

# Lambda

  Registration:
    Type: AWS::Serverless::Function
    Description: Creates and rotates tokens.
    Properties:
      CodeUri: ./src/registration
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContributorsTableName
        - SNSPublishMessagePolicy:
            TopicName: !Ref EmailServiceTopicArn
        - Statement:
            - Effect: Allow
              Action: ssm:GetParameter*
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/communitypatch/${Namespace}/*'
      Events:
        ApiContributorRegistration:
          Type: Api
          Properties:
            Path: /v1/register
            Method: post
            RequestModel:
              Model: Registration
              Required: true
            RestApiId:
                Ref: ApiGateway

  Verification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/verification
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContributorsTableName
        - SNSPublishMessagePolicy:
            TopicName: !Ref EmailServiceTopicArn
        - Statement:
            - Effect: Allow
              Action: ssm:GetParameter*
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/communitypatch/${Namespace}*'
      Events:
        ApiContributorRegistration:
          Type: Api
          Properties:
            Path: /v1/verify
            Method: get
            RestApiId:
                Ref: ApiGateway

  ApiContributorsGet:
    Type: AWS::Serverless::Function
    Description: List contributors on CommunityPatch.
    Properties:
      CodeUri: ./src/get_contributors
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ContributorsTableName
      Events:
        ApiContributorRegistration:
          Type: Api
          Properties:
            Path: /v1/contributors
            Method: get
            RestApiId:
              Ref: ApiGateway

