AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Regional setup and pre-requisites for a Community Patch region

Parameters:

  Namespace:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

# Need to figure out a solution for this region specific value. Manual for now.
#  CertificateId:
#    Type: String

Conditions:
  IsNotUsEast2:
    Fn::Not: !Equals [ $AWS::Region, 'us-east-2' ]
  IsNotEuCentral1:
    Fn::Not: !Equals [ $AWS::Region, 'eu-central-1' ]
  IsNotApSoutheast2:
    Fn::Not: !Equals [ $AWS::Region, 'ap-southeast-2' ]

Resources:

# S3 Buckets

  TitlesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Namespace}-communitypatch-${AWS::Region}-titles
      ReplicationConfiguration:
        Role: ''
        Rules:
          - Fn::If:
            - IsNotUsEast2
            - Destination:
                Bucket: !Sub ${Namespace}-communitypatch-us-east-2-titles
              Prefix: ''
              Status: Enabled
            - !Ref AWS::NoValue
          - Fn::If:
            - IsNotUsEast2
            - Destination:
                Bucket: !Sub ${Namespace}-communitypatch-eu-central-1-titles
              Prefix: ''
              Status: Enabled
            - !Ref AWS::NoValue
          - Fn::If:
            - IsNotUsEast2
            - Destination:
                Bucket: !Sub ${Namespace}-communitypatch-ap-southeast-2-titles
              Prefix: ''
              Status: Enabled
            - !Ref AWS::NoValue

# SSM Parameter Store

  PublishDomainName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/domain_name
      Type: String
      Value: !Ref DomainName

  PublishHostedZoneId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/hosted_zone_id
      Type: String
      Value: !Ref HostedZoneId

#  PublishCertificateId:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Name: !Sub /communitypatch/${Namespace}/certificate_id
#      Type: String
#      Value: !Ref CertificateId
