AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Regional setup and pre-requisites for a Community Patch region

Parameters:

  Namespace:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

# Need to figure out a solution for this region specific value. Manual for now.
#  CertificateId:
#    Type: String

Conditions:
  IsNotUsEast1: !Not [!Equals [ !Ref 'AWS::Region', 'us-east-1' ]]

Mappings:
  S3Rules:
    us-east-2:
      region1: eu-central-1
      region2: ap-southeast-2
    eu-central-1:
      region1: us-east-2
      region2: ap-southeast-2
    ap-southeast-2:
      region1: us-east-2
      region2: eu-central-1

Resources:

# S3 Buckets

  TitlesBucket:
    Type: AWS::S3::Bucket
    Condition: IsNotUsEast1
    Properties:
      BucketName: !Sub ${Namespace}-communitypatch-${AWS::Region}-titles
      ReplicationConfiguration:
        Role: ''
        Rules:
          - Destination:
              Bucket:
                Fn::Sub:
                  - arn:aws:s3:::${Namespace}-communitypatch-${Region}-titles
                  - { Region: !FindInMap [S3Rules, !Ref "AWS::Region", 'region1'] }
            Prefix: ''
            Status: Enabled
          - Destination:
              Bucket:
                Fn::Sub:
                  - arn:aws:s3:::${Namespace}-communitypatch-${Region}-titles
                  - { Region: !FindInMap [S3Rules, !Ref "AWS::Region", 'region2'] }
            Prefix: ''
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled

# SSM Parameter Store

  PublishDomainName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/domain_name
      Type: String
      Value: !Ref DomainName

  PublishHostedZoneId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/hosted_zone_id
      Type: String
      Value: !Ref HostedZoneId

#  PublishCertificateId:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Name: !Sub /communitypatch/${Namespace}/certificate_id
#      Type: String
#      Value: !Ref CertificateId
