AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Regional setup and pre-requisites for a Community Patch region

Parameters:

  Namespace:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

# Need to figure out a solution for this region specific value. Manual for now.
#  CertificateId:
#    Type: String

Resources:

# S3 Buckets

  TitlesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Namespace}-communitypatch-${AWS::Region}-titles
      VersioningConfiguration:
        Status: Enabled

# Lambda

  TitleSyncService:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: index.lambda_handler
      CodeUri: ./src/title_sync_service
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub ${Namespace}-communitypatch-*-titles
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref TitlesBucket
            Events:
              - s3:ObjectCreated:Put
              - s3:ObjectCreated:Post
              - s3:ObjectRemoved:Delete
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: titles


# SSM Parameter Store

  PublishDomainName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/domain_name
      Type: String
      Value: !Ref DomainName

  PublishHostedZoneId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/hosted_zone_id
      Type: String
      Value: !Ref HostedZoneId

#  PublishCertificateId:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Name: !Sub /communitypatch/${Namespace}/certificate_id
#      Type: String
#      Value: !Ref CertificateId

  PublishTitlesBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/titles_bucket_name
      Type: String
      Value: !Ref TitlesBucket
