AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Regional setup and pre-requisites for a Community Patch region

Parameters:

  Namespace:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

  CommunityPatchTableName:
    Type: String

# SAM Globals

Globals:
  Function:
    Runtime: python3.7
    Handler: index.lambda_handler
    Tracing: Active
    Environment:
      Variables:
        NAMESPACE: !Ref Namespace

Resources:

# Table Stream ARN Lookup

  DynamoDBStreamArnLookup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/stream_processor
      Policies:
        - Statement:
          - Effect: Allow
            Action: dynamodb:Describe*
            Resource: '*'

  CommunityPatchTableStream:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt DynamoDBStreamArnLookup.Arn
      TableName: !Ref CommunityPatchTableName

# EventBridge

  DataEvents:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub ${Namespace}-communitypatch

  TableStreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/stream_processor
      Policies:
        - Statement:
          - Effect: Allow
            Action: events:PutEvents
            Resource: !GetAtt DataEvents.Arn
      Events:
        DeploymentsTableEvent:
          Type: DynamoDB
          Properties:
            Stream: !Ref CommunityPatchTableStream
            StartingPosition: TRIM_HORIZON
            BatchSize: 10

