AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Jamf Pro endpoints for Community Patch

Parameters:

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

  RegionalCertificateArn:
    Type: AWS::SSM::Parameter::Value<String>

  CommunityPatchTableName:
    Type: String

# SAM Globals

Globals:
  Function:
    Runtime: python3.7
    Handler: index.lambda_handler
    Tracing: PassThrough
    Environment:
      Variables:
        COMMUNITY_PATCH_TABLE: !Ref CommunityPatchTableName

Resources:

# HTTP API

  Api:
    Type: AWS::Serverless::HttpApi

  ApiCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Sub 'jamf.${DomainName}'
      DomainNameConfigurations:
        - CertificateArn: !Ref RegionalCertificateArn
          EndpointType: REGIONAL

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref ApiCustomDomain
      ApiId: !Ref Api
      Stage: "$default"

  RegionalRoute53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub 'jamf.${DomainName}'
      SetIdentifier: !Sub 'jamf-api-${AWS::Region}'
      AliasTarget:
        DNSName: !GetAtt ApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ApiCustomDomain.RegionalHostedZoneId
      HostedZoneId: !Ref HostedZoneId
      Region: !Ref AWS::Region
      Type: A

# Lambda

  GetSoftware:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/get_software
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CommunityPatchTableName
      Events:
        GetAllSoftware:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor}/software
            Method: get
            ApiId: !Ref Api
        GetSelectSoftware:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor}/software/{titles}
            Method: get
            ApiId: !Ref Api

  GetPatch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/get_patch
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CommunityPatchTableName
      Events:
        GetPatch:
          Type: HttpApi
          Properties:
            Path: /v1/{contributor}/patch/{title}
            Method: get
            ApiId: !Ref Api
