AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Namespace:
    Type: String
    Description: Segments CloudFormation stack names and Parameter Store paths

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub '${Namespace}-communitypatch-${AWS::Region}-artifacts'
      LifecycleConfiguration:
        Rules:
          - Id: 14 day Lifecycle
            Prefix: /
            Status: Enabled
            ExpirationInDays: '14'
      VersioningConfiguration:
        Status: Enabled
