AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Regional setup and pre-requisites for a Community Patch region

Parameters:

  Namespace:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

# Need to figure out a solution for this region specific value. Manual for now.
#  CertificateId:
#    Type: String

Resources:

# SSM Parameter Store

  PublishDomainName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/domain_name
      Type: String
      Value: !Ref DomainName

  PublishHostedZoneId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /communitypatch/${Namespace}/hosted_zone_id
      Type: String
      Value: !Ref HostedZoneId

#  PublishCertificateId:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Name: !Sub /communitypatch/${Namespace}/certificate_id
#      Type: String
#      Value: !Ref CertificateId
